In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [6]:
df.tail(20)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
549         B       10.820         24.21           68.89      361.6   
550         B       10.860         21.48           68.51      360.5   
551         B       11.130         22.44           71.49      378.4   
552         B       12.770         29.43           81.35      507.9   
553         B        9.333         21.94           59.01      264.0   
554         B       12.880         28.92           82.50      514.3   
555         B       10.290         27.61           65.67      321.4   
556         B       10.160         19.59           64.73      311.7   
557         B        9.423         27.88           59.26      271.3   
558         B       14.590         22.68           96.39      657.1   
559         B       11.510         23.93           74.52      403.5   
560         B       14.050         27.15           91.38      600.4   
561         B       11.200         29.37           70.67      386.0   
562         M       15.220         30.62          103.40      716.9   
563         M       20.920         25.09          143.00     1347.0   
564         M       21.560         22.39          142.00     1479.0   
565         M       20.130         28.25          131.20     1261.0   
566         M       16.600         28.08          108.30      858.1   
567         M       20.600         29.33          140.10     1265.0   
568         B        7.760         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
549          0.08192           0.06602        0.015480              0.00816   
550          0.07431           0.04227        0.000000              0.00000   
551          0.09566           0.08194        0.048240              0.02257   
552          0.08276           0.04234        0.019970              0.01499   
553          0.09240           0.05605        0.039960              0.01282   
554          0.08123           0.05824        0.061950              0.02343   
555          0.09030           0.07658        0.059990              0.02738   
556          0.10030           0.07504        0.005025              0.01116   
557          0.08123           0.04971        0.000000              0.00000   
558          0.08473           0.13300        0.102900              0.03736   
559          0.09261           0.10210        0.111200              0.04105   
560          0.09929           0.11260        0.044620              0.04304   
561          0.07449           0.03558        0.000000              0.00000   
562          0.10480           0.20870        0.255000              0.09429   
563          0.10990           0.22360        0.317400              0.14740   
564          0.11100           0.11590        0.243900              0.13890   
565          0.09780           0.10340        0.144000              0.09791   
566          0.08455           0.10230        0.092510              0.05302   
567          0.11780           0.27700        0.351400              0.15200   
568          0.05263           0.04362        0.000000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
549         0.1976  ...        13.030          31.45            83.90   
550         0.1661  ...        11.660          24.77            74.08   
551         0.2030  ...        12.020          28.26            77.80   
552         0.1539  ...        13.870          36.00            88.10   
553         0.1692  ...         9.845          25.05            62.86   
554         0.1566  ...        13.890          35.74            88.84   
555         0.1593  ...        10.840          34.91            69.57   
556         0.1791  ...        10.650          22.88            67.88   
557         0.1742  ...        10.490          34.24            66.50   
558         0.1454  ...        15.480          27.27           105.90   
559         0.1388  ...        12.480          37

In [7]:
mid = len(df) // 2
n = 10
df.iloc[mid - n//2 : mid + n//2 + n % 2]

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
279         B        13.85         15.18           88.99      587.4   
280         M        19.16         26.60          126.20     1138.0   
281         B        11.74         14.02           74.24      427.3   
282         M        19.40         18.18          127.20     1145.0   
283         M        16.24         18.77          108.80      805.1   
284         B        12.89         15.70           84.08      516.6   
285         B        12.58         18.40           79.83      489.0   
286         B        11.94         20.76           77.87      441.0   
287         B        12.89         13.12           81.89      515.9   
288         B        11.26         19.96           73.72      394.1   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
279          0.09516           0.07688         0.04479             0.037110   
280          0.10200           0.14530         0.19210             0.096640   
281          0.07813           0.04340         0.02245             0.027630   
282          0.10370           0.14420         0.16260             0.094640   
283          0.10660           0.18020         0.19480             0.090520   
284          0.07818           0.09580         0.11150             0.033900   
285          0.08393           0.04216         0.00186             0.002924   
286          0.08605           0.10110         0.06574             0.037910   
287          0.06955           0.03729         0.02260             0.011710   
288          0.08020           0.11810         0.09274             0.055880   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
279         0.2110  ...         14.98          21.74            98.37   
280         0.1902  ...         23.72          35.90           159.80   
281         0.2101  ...         13.31          18.26            84.70   
282         0.1893  ...         23.79          28.65           152.40   
283         0.1876  ...         18.55          25.09           126.90   
284         0.1432  ...         13.90          19.69            92.12   
285         0.1697  ...         13.50          23.08            85.56   
286         0.1588  ...         13.24          27.29            92.20   
287         0.1337  ...         13.62          15.54            87.40   
288         0.2595  ...         11.86          22.33            78.27   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
279       670.0           0.11850            0.17240         0.145600   
280      1724.0           0.17820            0.38410         0.575400   
281       533.7           0.10360            0.08500         0.067350   
282      1628.0           0.15180            0.37490         0.431600   
283      1031.0           0.13650            0.47060         0.502600   
284       595.6           0.09926            0.23170         0.334400   
285       564.1           0.10380            0.06624         0.005579   
286       546.1           0.11160            0.28130         0.236500   
287       577.0           0.09616            0.11470         0.118600   
288       437.6           0.10280            0.18430         0.154600   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
279              0.099930          0.2955                  0.06912  
280              0.187200          0.3258                  0.09720  
281              0.082900          0.3101                  0.06688  
282              0.225200          0.3590                  0.07787  
283              0.173200          0.2770                  0.10630  
284              0.101700          0.1999                  0.07127  
285              0.008772          0.2505                  0.06431  
286              0.115500          0.2465                  0.09981  
287              0.053660          0.2309                  0.06915  
288              0.093140          0.2955             

### train test split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[-0.29398565, -0.15518968, -0.26739873, ...,  1.42913612,
         1.73915681,  1.85930022],
       [ 0.11126221,  0.78610706,  0.1632181 , ..., -0.05716064,
        -1.06562722, -0.20544092],
       [-0.04569999, -0.78272084, -0.11020911, ..., -0.60102732,
        -0.26792068, -0.62536979],
       ...,
       [ 1.81786936, -0.36358622,  1.67347945, ...,  1.08439994,
        -0.2252169 ,  0.2842943 ],
       [ 0.81616516,  0.39272932,  0.80066339, ...,  1.03450392,
        -0.44215208, -0.4263126 ],
       [-0.09992329,  0.06491453, -0.15571137, ..., -0.83735304,
        -0.6300487 , -0.80152177]])

In [11]:
X_train.shape

(455, 30)

In [12]:
y_train

47     M
558    B
437    B
410    B
94     M
      ..
317    M
6      M
1      M
335    M
438    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [13]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [14]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0,

In [15]:
y_train.shape

(455,)

In [16]:
a=np.expand_dims(y_train,1)

In [17]:
a.shape

(455, 1)

### Numpy arrays to PyTorch tensors

In [25]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [26]:
X_train_tensor.shape

torch.Size([455, 30])

In [27]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [34]:
import torch.nn as nn
class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()


  def forward(self, features):
    out=self.linear(features)
    out=self.sigmoid(out)

    return out

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss





### Important Parameters

In [35]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [36]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  # zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7643381953239441
Epoch: 2, Loss: 0.7387225031852722
Epoch: 3, Loss: 0.7227873206138611
Epoch: 4, Loss: 0.7127456665039062
Epoch: 5, Loss: 0.7061219215393066
Epoch: 6, Loss: 0.7014641165733337
Epoch: 7, Loss: 0.6979671716690063
Epoch: 8, Loss: 0.6951913833618164
Epoch: 9, Loss: 0.6928920745849609
Epoch: 10, Loss: 0.6909272074699402
Epoch: 11, Loss: 0.6892091631889343
Epoch: 12, Loss: 0.6876813769340515
Epoch: 13, Loss: 0.68630450963974
Epoch: 14, Loss: 0.6850504279136658
Epoch: 15, Loss: 0.6838985085487366
Epoch: 16, Loss: 0.6828330755233765
Epoch: 17, Loss: 0.6818418502807617
Epoch: 18, Loss: 0.680915355682373
Epoch: 19, Loss: 0.680046021938324
Epoch: 20, Loss: 0.6792279481887817
Epoch: 21, Loss: 0.6784559488296509
Epoch: 22, Loss: 0.6777260303497314
Epoch: 23, Loss: 0.6770347952842712
Epoch: 24, Loss: 0.6763792634010315
Epoch: 25, Loss: 0.6757569909095764


In [38]:
model.linear.weight

Parameter containing:
tensor([[-0.0702,  0.0187,  0.0084, -0.0458, -0.0663,  0.0975,  0.0125, -0.0094,
         -0.0021,  0.0144,  0.0549, -0.0168,  0.0257,  0.0701,  0.1202,  0.0331,
         -0.1059, -0.1253, -0.0839,  0.0463,  0.1060, -0.0099, -0.1414, -0.0310,
         -0.1291,  0.0672, -0.0753,  0.1452,  0.0808, -0.0237]],
       requires_grad=True)

In [39]:
model.linear.bias

Parameter containing:
tensor([-0.2197], requires_grad=True)

### Evaluation

In [40]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.640350878238678
