In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [ ]:
df.tail(20)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
549         B       10.820         24.21           68.89      361.6   
550         B       10.860         21.48           68.51      360.5   
551         B       11.130         22.44           71.49      378.4   
552         B       12.770         29.43           81.35      507.9   
553         B        9.333         21.94           59.01      264.0   
554         B       12.880         28.92           82.50      514.3   
555         B       10.290         27.61           65.67      321.4   
556         B       10.160         19.59           64.73      311.7   
557         B        9.423         27.88           59.26      271.3   
558         B       14.590         22.68           96.39      657.1   
559         B       11.510         23.93           74.52      403.5   
560         B       14.050         27.15           91.38      600.4   
561         B       11.200         29.37           70.67      386.0   
562         M       15.220         30.62          103.40      716.9   
563         M       20.920         25.09          143.00     1347.0   
564         M       21.560         22.39          142.00     1479.0   
565         M       20.130         28.25          131.20     1261.0   
566         M       16.600         28.08          108.30      858.1   
567         M       20.600         29.33          140.10     1265.0   
568         B        7.760         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
549          0.08192           0.06602        0.015480              0.00816   
550          0.07431           0.04227        0.000000              0.00000   
551          0.09566           0.08194        0.048240              0.02257   
552          0.08276           0.04234        0.019970              0.01499   
553          0.09240           0.05605        0.039960              0.01282   
554          0.08123           0.05824        0.061950              0.02343   
555          0.09030           0.07658        0.059990              0.02738   
556          0.10030           0.07504        0.005025              0.01116   
557          0.08123           0.04971        0.000000              0.00000   
558          0.08473           0.13300        0.102900              0.03736   
559          0.09261           0.10210        0.111200              0.04105   
560          0.09929           0.11260        0.044620              0.04304   
561          0.07449           0.03558        0.000000              0.00000   
562          0.10480           0.20870        0.255000              0.09429   
563          0.10990           0.22360        0.317400              0.14740   
564          0.11100           0.11590        0.243900              0.13890   
565          0.09780           0.10340        0.144000              0.09791   
566          0.08455           0.10230        0.092510              0.05302   
567          0.11780           0.27700        0.351400              0.15200   
568          0.05263           0.04362        0.000000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
549         0.1976  ...        13.030          31.45            83.90   
550         0.1661  ...        11.660          24.77            74.08   
551         0.2030  ...        12.020          28.26            77.80   
552         0.1539  ...        13.870          36.00            88.10   
553         0.1692  ...         9.845          25.05            62.86   
554         0.1566  ...        13.890          35.74            88.84   
555         0.1593  ...        10.840          34.91            69.57   
556         0.1791  ...        10.650          22.88            67.88   
557         0.1742  ...        10.490          34.24            66.50   
558         0.1454  ...        15.480          27.27           105.90   
559         0.1388  ...        12.480          37

In [ ]:
mid = len(df) // 2
n = 10
df.iloc[mid - n//2 : mid + n//2 + n % 2]

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
279         B        13.85         15.18           88.99      587.4   
280         M        19.16         26.60          126.20     1138.0   
281         B        11.74         14.02           74.24      427.3   
282         M        19.40         18.18          127.20     1145.0   
283         M        16.24         18.77          108.80      805.1   
284         B        12.89         15.70           84.08      516.6   
285         B        12.58         18.40           79.83      489.0   
286         B        11.94         20.76           77.87      441.0   
287         B        12.89         13.12           81.89      515.9   
288         B        11.26         19.96           73.72      394.1   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
279          0.09516           0.07688         0.04479             0.037110   
280          0.10200           0.14530         0.19210             0.096640   
281          0.07813           0.04340         0.02245             0.027630   
282          0.10370           0.14420         0.16260             0.094640   
283          0.10660           0.18020         0.19480             0.090520   
284          0.07818           0.09580         0.11150             0.033900   
285          0.08393           0.04216         0.00186             0.002924   
286          0.08605           0.10110         0.06574             0.037910   
287          0.06955           0.03729         0.02260             0.011710   
288          0.08020           0.11810         0.09274             0.055880   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
279         0.2110  ...         14.98          21.74            98.37   
280         0.1902  ...         23.72          35.90           159.80   
281         0.2101  ...         13.31          18.26            84.70   
282         0.1893  ...         23.79          28.65           152.40   
283         0.1876  ...         18.55          25.09           126.90   
284         0.1432  ...         13.90          19.69            92.12   
285         0.1697  ...         13.50          23.08            85.56   
286         0.1588  ...         13.24          27.29            92.20   
287         0.1337  ...         13.62          15.54            87.40   
288         0.2595  ...         11.86          22.33            78.27   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
279       670.0           0.11850            0.17240         0.145600   
280      1724.0           0.17820            0.38410         0.575400   
281       533.7           0.10360            0.08500         0.067350   
282      1628.0           0.15180            0.37490         0.431600   
283      1031.0           0.13650            0.47060         0.502600   
284       595.6           0.09926            0.23170         0.334400   
285       564.1           0.10380            0.06624         0.005579   
286       546.1           0.11160            0.28130         0.236500   
287       577.0           0.09616            0.11470         0.118600   
288       437.6           0.10280            0.18430         0.154600   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
279              0.099930          0.2955                  0.06912  
280              0.187200          0.3258                  0.09720  
281              0.082900          0.3101                  0.06688  
282              0.225200          0.3590                  0.07787  
283              0.173200          0.2770                  0.10630  
284              0.101700          0.1999                  0.07127  
285              0.008772          0.2505                  0.06431  
286              0.115500          0.2465                  0.09981  
287              0.053660          0.2309                  0.06915  
288              0.093140          0.2955             

### train test split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[-0.69983586, -1.46191801, -0.70873053, ..., -0.44087594,
        -0.19789501,  0.20738027],
       [-0.31414594, -0.72813168, -0.34349814, ..., -0.1119679 ,
         0.76263969,  0.65859594],
       [ 1.05719602,  2.04318085,  1.07426759, ...,  1.31210575,
         0.11807035,  0.38121819],
       ...,
       [-0.37985607, -0.34739349, -0.43314609, ..., -1.19451316,
        -1.15684988, -1.2808685 ],
       [ 0.89720613,  0.66790835,  0.83769661, ...,  1.3339187 ,
         0.50354809, -0.43892622],
       [ 0.28295921, -0.56199138,  0.30354424, ..., -0.17117446,
        -1.13789196,  0.09457636]])

In [ ]:
X_train.shape

(455, 30)

In [ ]:
y_train

98     B
292    B
446    M
313    B
71     B
      ..
354    B
458    B
429    B
264    M
500    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [ ]:
y_train.shape

(455,)

In [ ]:
a=np.expand_dims(y_train,1)

In [ ]:
a.shape

(455, 1)

### Numpy arrays to PyTorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [ ]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss





### Important Parameters

In [ ]:
learning_rate = 0.1
epochs = 75

### Training Pipeline

In [ ]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.3408954871684826
Epoch: 2, Loss: 3.2161157406323864
Epoch: 3, Loss: 3.0824221845597872
Epoch: 4, Loss: 2.945018982890057
Epoch: 5, Loss: 2.803334350693749
Epoch: 6, Loss: 2.656808043052136
Epoch: 7, Loss: 2.5050208711222552
Epoch: 8, Loss: 2.3553853936848537
Epoch: 9, Loss: 2.204267834634037
Epoch: 10, Loss: 2.045802333498813
Epoch: 11, Loss: 1.891585038507003
Epoch: 12, Loss: 1.7443495250463035
Epoch: 13, Loss: 1.603109190028119
Epoch: 14, Loss: 1.4657043017054712
Epoch: 15, Loss: 1.340296876746733
Epoch: 16, Loss: 1.2281049636217172
Epoch: 17, Loss: 1.1273696295848976
Epoch: 18, Loss: 1.0417840745876719
Epoch: 19, Loss: 0.9704112975577032
Epoch: 20, Loss: 0.9144418070559065
Epoch: 21, Loss: 0.871855087077026
Epoch: 22, Loss: 0.8401500731463865
Epoch: 23, Loss: 0.8167551598406041
Epoch: 24, Loss: 0.7993627986191235
Epoch: 25, Loss: 0.7861263744223607
Epoch: 26, Loss: 0.7757035770385147
Epoch: 27, Loss: 0.7671864564765831
Epoch: 28, Loss: 0.7599880499880856
Epoch: 29,

In [ ]:
model.weights

tensor([[ 0.4286],
        [ 0.1100],
        [ 0.3848],
        [ 0.1779],
        [-0.0146],
        [-0.3188],
        [-0.4186],
        [-0.3207],
        [ 0.3120],
        [ 0.1093],
        [ 0.1062],
        [ 0.2225],
        [-0.2151],
        [-0.2747],
        [ 0.2252],
        [-0.1587],
        [ 0.4459],
        [-0.3891],
        [ 0.0253],
        [ 0.1140],
        [-0.4858],
        [-0.2708],
        [ 0.3772],
        [ 0.2054],
        [ 0.1865],
        [ 0.1446],
        [ 0.1554],
        [ 0.0299],
        [-0.1142],
        [-0.0144]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.4276], dtype=torch.float64, requires_grad=True)

### Evaluation

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.6034164428710938
