In [19]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out=self.sigmoid(out)

    return out

In [20]:
# create dataset
torch.manual_seed(100)
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5502],
        [0.5112],
        [0.5238],
        [0.5442],
        [0.5230],
        [0.5435],
        [0.4954],
        [0.5686],
        [0.4973],
        [0.4863]], grad_fn=<SigmoidBackward0>)

In [21]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[-0.0492,  0.2038, -0.0391, -0.1441,  0.1084]], requires_grad=True)

In [22]:
model.linear.bias

Parameter containing:
tensor([0.0474], requires_grad=True)

In [23]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [24]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [25]:
# create dataset
torch.manual_seed(100)
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5677],
        [0.5327],
        [0.5795],
        [0.5446],
        [0.5801],
        [0.5468],
        [0.5567],
        [0.5691],
        [0.5583],
        [0.5747]], grad_fn=<SigmoidBackward0>)

In [26]:
# show model weights
model.linear1.weight

Parameter containing:
tensor([[-0.0492,  0.2038, -0.0391, -0.1441,  0.1084],
        [ 0.0474,  0.1696, -0.1174,  0.3625,  0.3001],
        [-0.1754,  0.1544,  0.0662,  0.3786,  0.3737]], requires_grad=True)

In [27]:
# show model weights
model.linear2.weight

Parameter containing:
tensor([[-0.1872, -0.3267,  0.5143]], requires_grad=True)

In [28]:
model.linear1.bias

Parameter containing:
tensor([0.2317, 0.2482, 0.1054], requires_grad=True)

In [29]:
model.linear2.bias

Parameter containing:
tensor([0.2443], requires_grad=True)

In [30]:
!pip install torchinfo

In [31]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [32]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [33]:
# create dataset
torch.manual_seed(100)
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5677],
        [0.5327],
        [0.5795],
        [0.5446],
        [0.5801],
        [0.5468],
        [0.5567],
        [0.5691],
        [0.5583],
        [0.5747]], grad_fn=<SigmoidBackward0>)