In [2]:
import torch
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. using cpu")

GPU is available
Using GPU: Tesla T4


# Creating a Tensor

In [4]:
a=torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
torch.rand(2,3)

tensor([[0.2300, 0.7860, 0.9201],
        [0.7474, 0.7615, 0.2984]])

In [10]:
#for reproducibility
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.manual_seed(200)
torch.rand(2,3)

tensor([[0.5939, 0.5008, 0.9961],
        [0.0311, 0.1716, 0.9481]])

In [14]:
torch.manual_seed(200)
torch.rand(2,3)

tensor([[0.5939, 0.5008, 0.9961],
        [0.0311, 0.1716, 0.9481]])

In [15]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,3))

# using linspace
print("using linspace ->", torch.linspace(1,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 3, 6, 9])
using linspace -> tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tensor Shape

In [17]:
x=torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [18]:
x.shape

torch.Size([2, 5])

In [19]:
torch.empty_like(x)

tensor([[137036475329968, 137036475329968,       140005584,       139893056,
                       0],
        [      139890016,       114042704, 137032058354768,               0,
                       0]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])

In [22]:
torch.rand_like(x, dtype=torch.float64)
##need for datatype

tensor([[0.1762, 0.9601, 0.8585, 0.0037, 0.0551],
        [0.0539, 0.7319, 0.3471, 0.3843, 0.8502]], dtype=torch.float64)

# Tensor Data Types

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [23]:
# find data type
x.dtype

torch.int64

In [24]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [26]:
# using to()
x.to(torch.float32)

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

# Mathematical Operation

### 1. Scalar operation

---



In [27]:
x = torch.rand(2,2)
x

tensor([[0.7455, 0.8324],
        [0.6025, 0.5628]])

In [28]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.5558, 0.6929],
        [0.3630, 0.3168]])

### 2. Element wise operation

In [29]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.0328, 0.9285, 0.1075],
        [0.7076, 0.1293, 0.7931]])
tensor([[0.5836, 0.4422, 0.5337],
        [0.8569, 0.4688, 0.5481]])


In [30]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0328, 0.0441, 0.1075],
        [0.7076, 0.1293, 0.2451]])

In [31]:
c = torch.tensor([1, -2, 3, -4])

In [32]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [33]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [34]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [35]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [36]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [37]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [38]:
# clamp
torch.clamp(d, min=2, max=3)
#used to clamp a tensor, i.e. value below 2 will become 2 and value above 3 will become 3

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [39]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[9., 1., 1.],
        [6., 0., 1.]])

In [40]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([11.,  7.])

In [41]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([7.5000, 0.5000, 1.0000])

In [42]:
# median
torch.median(e)
#median along row
torch.median(e, dim=1)

torch.return_types.median(
values=tensor([1., 1.]),
indices=tensor([2, 2]))

In [43]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [44]:
# product
torch.prod(e)

tensor(0.)

In [45]:
# standard deviation
torch.std(e)

tensor(3.6332)

In [46]:
# variance
torch.var(e)

tensor(13.2000)

In [47]:
# argmax
torch.argmax(e)

tensor(0)

In [48]:
# argmin
torch.argmin(e)

tensor(4)

### 4. Matrix operations

In [49]:
torch.manual_seed(100)
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[0, 2, 5],
        [9, 5, 1]])
tensor([[2, 8],
        [8, 0],
        [4, 3]])


In [50]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[36, 15],
        [62, 75]])

In [51]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [52]:
# transpose
torch.transpose(f, 0, 1)

tensor([[0, 9],
        [2, 5],
        [5, 1]])

In [53]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[8., 8., 4.],
        [4., 1., 0.],
        [4., 3., 8.]])

In [54]:
# determinant
torch.det(h)

tensor(-160.)

In [55]:
# inverse
torch.inverse(h)

tensor([[-0.0500,  0.3250,  0.0250],
        [ 0.2000, -0.3000, -0.1000],
        [-0.0500, -0.0500,  0.1500]])

### 5. Comparison operations

In [56]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 4, 6],
        [0, 1, 9]])
tensor([[9, 8, 0],
        [7, 0, 0]])


In [57]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [58]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[9., 5., 7.],
        [3., 9., 4.]])

In [59]:
# log
torch.log(k)

tensor([[2.1972, 1.6094, 1.9459],
        [1.0986, 2.1972, 1.3863]])

In [60]:
# exp
torch.exp(k)

tensor([[8103.0840,  148.4132, 1096.6332],
        [  20.0855, 8103.0840,   54.5981]])

In [61]:
# sqrt
torch.sqrt(k)

tensor([[3.0000, 2.2361, 2.6458],
        [1.7321, 3.0000, 2.0000]])

In [62]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.9933, 0.9991],
        [0.9526, 0.9999, 0.9820]])

In [63]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9975, 0.0180, 0.9526],
        [0.0025, 0.9820, 0.0474]])

In [64]:
# relu
torch.relu(k)

tensor([[9., 5., 7.],
        [3., 9., 4.]])

In [65]:
#tanh
torch.tanh(k)

tensor([[1.0000, 0.9999, 1.0000],
        [0.9951, 1.0000, 0.9993]])

## Inplace Operations

In [66]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.8902, 0.5163, 0.0359],
        [0.6476, 0.3430, 0.3182]])
tensor([[0.5261, 0.0447, 0.5123],
        [0.9051, 0.5989, 0.4450]])


In [67]:
m.add_(n)

tensor([[1.4163, 0.5609, 0.5482],
        [1.5527, 0.9419, 0.7632]])

In [68]:
m

tensor([[1.4163, 0.5609, 0.5482],
        [1.5527, 0.9419, 0.7632]])

In [69]:
n

tensor([[0.5261, 0.0447, 0.5123],
        [0.9051, 0.5989, 0.4450]])

In [70]:
torch.relu(m)

tensor([[1.4163, 0.5609, 0.5482],
        [1.5527, 0.9419, 0.7632]])

In [71]:
m.relu_()

tensor([[1.4163, 0.5609, 0.5482],
        [1.5527, 0.9419, 0.7632]])

In [72]:
m

tensor([[1.4163, 0.5609, 0.5482],
        [1.5527, 0.9419, 0.7632]])

## Copying a Tensor

In [73]:
a = torch.rand(2,3)
a

tensor([[0.7278, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896]])

In [75]:
b = a

In [76]:
b

tensor([[0.7278, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896]])

In [77]:
a[0][0] = 0

In [78]:
a

tensor([[0.0000, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896]])

In [79]:
b

tensor([[0.0000, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896]])

In [80]:
id(a)

137032058355152

In [81]:
id(b)

137032058355152

In [82]:
b=a.clone()

In [83]:
a

tensor([[0.0000, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896]])

In [84]:
b

tensor([[0.0000, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896]])

In [85]:
a[0][0] = 10

In [86]:
a

tensor([[10.0000,  0.4563,  0.3389],
        [ 0.6211,  0.5530,  0.6896]])

In [87]:
b

tensor([[0.0000, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896]])

In [88]:
id(a)

137032058355152

In [89]:
id(b)

137031406915792

##Tensor Operation on GPU

In [90]:
torch.cuda.is_available()

True

In [91]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [92]:
#on gpu
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [93]:
a=torch.rand((2,3))
a

tensor([[0.3687, 0.9053, 0.8356],
        [0.3039, 0.6726, 0.5740]])

In [94]:
#moving cpu tensor to gpu
a.to(device)


tensor([[0.3687, 0.9053, 0.8356],
        [0.3039, 0.6726, 0.5740]], device='cuda:0')

In [96]:
import torch
import time

Size = 1000  # Reduce size if memory error occurs

# CPU computation
device_cpu = torch.device("cpu")
matrix_a_cpu = torch.rand(Size, Size, device=device_cpu)
matrix_b_cpu = torch.rand(Size, Size, device=device_cpu)

start_time = time.time()
matrix_c_cpu = torch.matmul(matrix_a_cpu, matrix_b_cpu)
cpu_time = time.time() - start_time

# GPU computation
if torch.cuda.is_available():
    device_gpu = torch.device("cuda")
    matrix_a_gpu = torch.rand(Size, Size, device=device_gpu)
    matrix_b_gpu = torch.rand(Size, Size, device=device_gpu)

    torch.cuda.synchronize()
    start_time = time.time()
    matrix_c_gpu = torch.matmul(matrix_a_gpu, matrix_b_gpu)
    torch.cuda.synchronize()
    gpu_time = time.time() - start_time

    print(f"CPU Time: {cpu_time:.6f} seconds")
    print(f"GPU Time: {gpu_time:.6f} seconds")
else:
    print("CUDA is not available. Run the script on a GPU-enabled device.")


CPU Time: 0.051150 seconds
GPU Time: 0.000953 seconds


In [97]:
cpu_time/gpu_time

53.688688688688686

##Reshaping Tensor

In [98]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
#reshape
a.reshape(2,2,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [100]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [102]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [103]:
b=torch.rand(2,3,4)
b

tensor([[[0.1516, 0.6378, 0.7503, 0.9413],
         [0.3477, 0.8787, 0.8132, 0.9034],
         [0.0351, 0.9968, 0.6104, 0.7923]],

        [[0.2537, 0.9081, 0.3866, 0.4332],
         [0.2894, 0.7623, 0.3318, 0.8176],
         [0.6792, 0.0689, 0.7718, 0.9885]]])

In [104]:
b.permute(2,0,1)

tensor([[[0.1516, 0.3477, 0.0351],
         [0.2537, 0.2894, 0.6792]],

        [[0.6378, 0.8787, 0.9968],
         [0.9081, 0.7623, 0.0689]],

        [[0.7503, 0.8132, 0.6104],
         [0.3866, 0.3318, 0.7718]],

        [[0.9413, 0.9034, 0.7923],
         [0.4332, 0.8176, 0.9885]]])

In [106]:
b.shape

torch.Size([2, 3, 4])

In [107]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [108]:
b.permute(0,1,2)

tensor([[[0.1516, 0.6378, 0.7503, 0.9413],
         [0.3477, 0.8787, 0.8132, 0.9034],
         [0.0351, 0.9968, 0.6104, 0.7923]],

        [[0.2537, 0.9081, 0.3866, 0.4332],
         [0.2894, 0.7623, 0.3318, 0.8176],
         [0.6792, 0.0689, 0.7718, 0.9885]]])

In [109]:
#unsqueeze
c=torch.rand(226,226,3)

In [112]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [117]:
c.unsqueeze(-4).shape

torch.Size([1, 226, 226, 3])

In [119]:
#squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

##Numpy & PyTorch

In [120]:
import numpy as np

In [121]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [122]:
b=a.numpy()

In [123]:
type(b)

numpy.ndarray

In [124]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [125]:
d=torch.from_numpy(c)
d

tensor([1, 2, 3])